feat: allow to upload larger images without cropping any part of the image
cesium/CeSIUMpeloMundo pull request #102
Opened 2024-07-23 16:50 UTC by AfonsoMartins26

2024-07-28 21:53 UTC, MarioRodrigues10 commented
First of all, i really like the improvements that you made, but let's review a few things.

1) I think it will be good to keep the same layout for vertical images, and use a similar layout to horizontal images.
![image](https://github.com/user-attachments/assets/5b2ac9e1-45d6-4b00-969d-d8f3dfadc6dd)

2) The use case should be like, I upload a picture to be added to CeSIUMPeloMundo and you choose the picture orientation, by default is vertical, in case it's horizontal you display the layout that you showed us by using the same design Diogo did previously.

You can make that by adding a prop either to json and the function that parses the pictures.  

What's your thoughts on it? @AfonsoMartins26

2024-07-30 12:18 UTC, MarioRodrigues10 commented
It looks amazing @AfonsoMartins26  🙌  !!
Great job 🤩

2024-07-30 13:17 UTC, MarioRodrigues10 requested changes

2024-07-30 13:17 UTC, MarioRodrigues10 commented on components/Marker/Marker.tsx
> +  orientation = 'default' // Default to 'default' orientation
```suggestion
  orientation = 'vertical'
```
Vertical should be the default orientation

2024-07-30 14:26 UTC, MarioRodrigues10 submitted a review, later dismissed
This looks good to me ✅ , but let the other reviewers @diogogmatos , @joaodiaslobo and @ruilopesm take a look into it !! 🙌

2024-08-06 14:17 UTC, joaodiaslobo requested changes
The image now has some odd white borders on its corners, can you fix that?
Also, I think the location text looks less clear than before, missing a shadow maybe?

New:
![image](https://github.com/user-attachments/assets/21cfe21d-3d49-450d-a143-3a0c9e45a8be)
Old:
![image](https://github.com/user-attachments/assets/4ce37975-bc25-421d-969a-445a54ebcfa6)

2024-08-06 14:28 UTC, joaodiaslobo requested changes
Also, I wonder if it would be possible to maybe discover the orientation of the image automatically through its width and height? 🤔

2024-08-06 14:33 UTC, joaodiaslobo requested changes
Popover is way too small on mobile devices.

New | Old
![image](https://github.com/user-attachments/assets/47e1b3fe-c4e0-46f7-bdac-c5eae5437180)

2024-08-06 17:40 UTC, AfonsoMartins26 commented
> Also, I wonder if it would be possible to maybe discover the orientation of the image automatically through its width and height? 🤔

In my initial pr, I implemented the feature. However, @MarioRodrigues10 said:
"The use case should work as follows: When uploading a picture to be added to CeSIUMPeloMundo, you should be able to choose the picture orientation. The default orientation should be vertical. In cases where the picture is horizontal, you should display the layout you showed us earlier, using the same design that Diogo previously implemented."

2024-08-06 17:49 UTC, AfonsoMartins26 commented
Pc and mobile changes:
![Screenshot from 2024-08-06 18-46-18](https://github.com/user-attachments/assets/c016c6ba-8b1f-41d3-9b46-988ddfcfb26c)
![Screenshot from 2024-08-06 18-47-15](https://github.com/user-attachments/assets/5569637f-37c8-4ea4-b02a-fbf8eee6822c)

2024-08-07 23:58 UTC, joaodiaslobo requested changes
Text looks cool and no more white borders, great! 🎉
But now, the image is way too big on mobile, to the point where it gets out of the screen:
![image](https://github.com/user-attachments/assets/08f8752b-a54c-4c95-86d7-2a622119b256)
![image](https://github.com/user-attachments/assets/08b8a8fe-4b9c-440b-89c9-5ca24a4ef6ea)

How it should look:
![image](https://github.com/user-attachments/assets/9dffa301-f219-4c06-b628-2dd6b64795bb)

I have used iPhone SE resolution for these examples.
Just make sure it fits and this PR should be good to go!! 🙏

2024-08-14 19:26 UTC, ruilopesm reviewed
It would be very nice and clever trying to guess the orientation of the photo fully based on its dimensions 👀

2024-08-17 22:16 UTC, MarioRodrigues10 commented
@ruilopesm  I had the same thought initially, but I changed my mind when thinking about some edge cases.
First of all in case where is a squared image, how will it would be defined by default?

Now let's imagine I have a horizontal picture but I want only to show part of it as a vertical image, the automatically display would put it by default has a horizontal picture.

I would like to give the user the ability to choose which orientation of the picture he wants.

2024-08-17 22:20 UTC, ruilopesm commented
@MarioRodrigues10 I think we can guess the best orientation by the image's aspect ratio. If perfect, let it be vertical. As for the other part, about the user deciding which orientation they want - we can let the user decide it, and if no orientation is defined, we automatically _calculate_ one. Nonetheless, we can also have an opinion about the best orientation when reviewing future PRs. What do you think? 👀

2024-08-18 00:06 UTC, MarioRodrigues10 commented
@ruilopesm it seems good, so let's resume it, basically if the user doesn't pass the orientation as prop it will automatically decide which one fits better. 
If the user decides to pass the orientation as prop we use the one the user has decided.

2024-09-02 13:02 UTC, MarioRodrigues10 requested changes

2024-09-02 13:02 UTC, MarioRodrigues10 commented on styles/globals.css
Add this to remove the white border
```css
.leaflet-popup-content-wrapper, .leaflet-popup-tip {
  background: transparent !important;
  border: none !important;
  border-radius: 12px;
}
```

2024-09-02 14:33 UTC, MarioRodrigues10 requested changes

2024-09-02 14:33 UTC, MarioRodrigues10 commented on components/Marker/Marker.tsx
> +  const [width, height] = popupClassName.split(':').map(Number);
```suggestion
  const handleImageLoad = (img: HTMLImageElement): void => {
    setImageOrientation(img.width > img.height ? 'horizontal' : 'vertical');
  }

  useEffect(() => {
    if(orientation || !photo) return;

    const img = new window.Image();
    img.src = photo;

    img.onload = () => handleImageLoad(img);
  }, [photo, orientation]);

  const popupClassName = useMemo(() => imageOrientation === 'horizontal' ? '651:400' : '301:470', [imageOrientation]);

  const [width, height] = useMemo(() => popupClassName.split(':').map(Number), [popupClassName]);
```

2024-09-03 11:21 UTC, joaodiaslobo requested changes
On mobile, the images are **always** vertical, even when the `orientation` is explicitly set as `horizontal` on the data. Is this behavior intended? 🤔

2024-09-06 19:33 UTC, MarioRodrigues10 requested changes
![image](https://github.com/user-attachments/assets/3faea427-560e-47cc-9d58-9590d9026c76)
Overlay text needs to be adjust to the mobile perspective. 🙌

2024-09-10 19:44 UTC, diogogmatos commented
![image](https://github.com/user-attachments/assets/a29270fc-6520-40be-952f-9d3d1d31691a)

Long text is looking weird when it wraps around. Don't know if this was an existing problem or a new problem though ahaha.

2024-09-11 09:26 UTC, diogogmatos reviewed
![image](https://github.com/user-attachments/assets/b1349114-e0cd-4318-8309-5821f4d3aa91)

In some pins the image shows up sideways even though the picture orientation is correct in the picture file. This is something that already happens in the deployed version but it would be cool to fix it too since we're messing with this.

2024-09-11 09:30 UTC, MarioRodrigues10 requested changes

2024-09-11 09:30 UTC, MarioRodrigues10 commented on components/Marker/Marker.tsx
> +  }, [imageOrientation]);
```suggestion
  const popupClassName = useMemo(() => {
    const isMobile = window.innerWidth <= 500;

    const sizeMapping = isMobile ? mobileSizes : desktopSizes;
    return imageOrientation === 'horizontal' ? sizeMapping.horizontal : sizeMapping.vertical;
  }, [imageOrientation]);
```

2024-09-11 09:30 UTC, MarioRodrigues10 commented on components/Marker/Marker.tsx
```suggestion
    const mobileSizes = {
      horizontal: '401:250',
      vertical: '351:550',
    };

    const desktopSizes = {
      horizontal: '651:400',
      vertical: '301:470',
    };
```

2024-09-11 09:32 UTC, joaodiaslobo commented
> In some pins the image shows up sideways even though the picture orientation is correct in the picture file. This is something that already happens in the deployed version but it would be cool to fix it too since we're messing with this.


@diogogmatos 
Pretty sure this is already fixed in this PR!

2024-09-11 09:34 UTC, diogogmatos commented
> > In some pins the image shows up sideways even though the picture orientation is correct in the picture file. This is something that already happens in the deployed version but it would be cool to fix it too since we're messing with this.
> 
> 
> 
> 
> 
> @diogogmatos 
> 
> Pretty sure this is already fixed in this PR!
> 
> 

The screenshot was from the deploy preview on this PR...

2024-09-11 09:41 UTC, joaodiaslobo commented
> The screenshot was from the deploy preview on this PR...

@diogogmatos 
Interesting, locally it does in fact use the right orientation but in the deploy preview it doesn't. 🤔

2024-09-14 23:52 UTC, diogogmatos reviewed
Seems to be fixed! Just make sure the checks pass ;)

2024-09-15 16:02 UTC, MarioRodrigues10 commented
Yes problem seems to be fixed @diogogmatos, I think @joaodiaslobo requested him to remove one or two lines and fix the CI, and after that it's good to go. :raised_hands:

2024-09-16 17:33 UTC, joaodiaslobo approved these changes
What a great addition! 🤩

2024-09-16 17:35 UTC, merged