fix: sorting select
cesium/CeSIUMpeloMundo pull request #98
Opened 2024-02-21 16:34 UTC by nunom27

fixes #74

2024-02-21 22:20 UTC, diogogmatos commented
So when I was reviewing this I figured out that I was legit just stupid when I tried to fix this last time because the first time I looked at this now I figured it out immediately, what you did works and is basically the same thing I'm going to suggest you:

So, normally in React when we use a `<select>` (or any other element with an associated value for that matter) we associate its value to a `useState` variable, so the value of the variable and the value of the `<select>` element are linked. Since they weren't, whenever `sortDirection` was changed and we closed and re-opened the Sidebar, the `<select>` value would default to the value of the first `<option>`. The optimal solution is to add `value={sortDirection}` as an attribute of `<select>`. What you did is basically that, but by manually setting that `<option>` as selected, which isn't good practice.

Very well noticed tho ;)

When you can, please make that change :rocket: :raised_hands:

2024-02-21 22:20 UTC, diogogmatos requested changes
So when I was reviewing this I figured out that I was legit just stupid when I tried to fix this last time because the first time I looked at this now I figured it out immediately, what you did works and is basically the same thing I'm going to suggest you:

So, normally in React when we use a <select> (or any other element with an associated value for that matter) we associate its value to a useState variable, so the value of the variable and the value of the <select> element are linked. Since they weren't, whenever sortDirection was changed and we closed and re-opened the Sidebar, the <select> value would default to the value of the first <option>. The optimal solution is to add value={sortDirection} as an attribute of <select>. What you did is basically that, but by manually setting that <option> as selected, which isn't good practice.

Very well noticed tho ;)

When you can, please make that change 🚀 🙌

2024-02-21 22:25 UTC, diogogmatos commented on components/Sidebar/Sidebar.tsx
>                    >
```suggestion
                    value={sortDirection}
                  >
```

2024-03-04 18:29 UTC, joaodiaslobo approved these changes
Thank you for your contribution!! 🧡🚀

2024-03-04 18:32 UTC, merged